---
kind: PersistentVolume
apiVersion: v1
metadata:
  namespace: cadanac-v0-1
  name: cadanac-pv
  labels:
    type: local
    name: cadanacvolume
spec:
  capacity:
    storage: 400Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /home/gcpdev/cadanac_local_pv
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - instance-cadanac-1

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: cadanac-v0-1
  name: cadanac-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 400Mi
  selector:
    matchLabels:
      name: cadanacvolume
