---
apiVersion: v1
kind: Service
metadata:
  name: blockchain-ca
  namespace: cadanac-v0-1
  labels:
    run: blockchain-ca
spec:
  type: NodePort
  selector:
    name: ca
  ports:
  - protocol: TCP
    nodePort: 30054
    targetPort: 7054
    port: 30054
    name: grpc
---
apiVersion: v1
kind: Service
metadata:
  name: blockchain-orderer
  namespace: cadanac-v0-1
  labels:
    run: blockchain-orderer
spec:
  type: NodePort
  selector:
    name: orderer
  ports:
  - protocol: TCP
    nodePort: 31010
    targetPort: 31010
    port: 31010
    name: grpc
---
apiVersion: v1
kind: Service
metadata:
  namespace: cadanac-v0-1
  name: blockchain-cpc1peer1
  labels:
    run: blockchain-cpc1peer1
spec:
  type: NodePort
  selector:
    name: cpc1peer1
  ports:
  - protocol: TCP
    nodePort: 30510
    targetPort: 30510
    port: 30510
    name: grpc
  - protocol: TCP
    nodePort: 30511
    targetPort: 30511
    port: 30511
    name: events

---
apiVersion: v1
kind: Service
metadata:
  namespace: cadanac-v0-1
  name: blockchain-cpc2peer1
  labels:
    run: blockchain-cpc2peer1
spec:
  type: NodePort
  selector:
    name: cpc2peer1
  ports:
  - protocol: TCP
    nodePort: 30610
    targetPort: 30610
    port: 30610
    name: grpc
  - protocol: TCP
    nodePort: 30611
    targetPort: 30611
    port: 30611
    name: events

---
apiVersion: v1
kind: Service
metadata:
  namespace: cadanac-v0-1
  name: blockchain-cpc3peer1
  labels:
    run: blockchain-cpc3peer1
spec:
  type: NodePort
  selector:
    name: cpc3peer1
  ports:
  - protocol: TCP
    nodePort: 30710
    targetPort: 30710
    port: 30710
    name: grpc
  - protocol: TCP
    nodePort: 30711
    targetPort: 30711
    port: 30711
    name: events

---
apiVersion: v1
kind: Service
metadata:
  namespace: cadanac-v0-1
  name: blockchain-hosp1peer1
  labels:
    run: blockchain-hosp1peer1
spec:
  type: NodePort
  selector:
    name: hosp1peer1
  ports:
  - protocol: TCP
    nodePort: 30810
    targetPort: 30810
    port: 30810
    name: grpc
  - protocol: TCP
    nodePort: 30811
    targetPort: 30811
    port: 30811
    name: events

---
apiVersion: v1
kind: Service
metadata:
  namespace: cadanac-v0-1
  name: blockchain-hosp2peer1
  labels:
    run: blockchain-hosp2peer1
spec:
  type: NodePort
  selector:
    name: hosp2peer1
  ports:
  - protocol: TCP
    nodePort: 30910
    targetPort: 30910
    port: 30910
    name: grpc
  - protocol: TCP
    nodePort: 30911
    targetPort: 30911
    port: 30911
    name: events

---
apiVersion: v1
kind: Service
metadata:
  namespace: cadanac-v0-1
  name: blockchain-ngo1peer1
  labels:
    run: blockchain-ngo1peer1
spec:
  type: NodePort
  selector:
    name: ngo1peer1
  ports:
  - protocol: TCP
    nodePort: 31310
    targetPort: 31310
    port: 31310
    name: grpc
  - protocol: TCP
    nodePort: 31311
    targetPort: 31311
    port: 31311
    name: events

---
apiVersion: v1
kind: Service
metadata:
  namespace: cadanac-v0-1
  name: blockchain-ngo2peer1
  labels:
    run: blockchain-ngo2peer1
spec:
  type: NodePort
  selector:
    name: ngo2peer1
  ports:
  - protocol: TCP
    nodePort: 31110
    targetPort: 31110
    port: 31110
    name: grpc
  - protocol: TCP
    nodePort: 31111
    targetPort: 31111
    port: 31111
    name: events

---
apiVersion: v1
kind: Service
metadata:
  namespace: cadanac-v0-1
  name: blockchain-gov1peer1
  labels:
    run: blockchain-gov1peer1
spec:
  type: NodePort
  selector:
    name: gov1peer1
  ports:
  - protocol: TCP
    nodePort: 31210
    targetPort: 31210
    port: 31210
    name: grpc
  - protocol: TCP
    nodePort: 31211
    targetPort: 31211
    port: 31211
    name: events
