---
################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:

    # SampleOrg defines an MSP using the sampleconfig.  It should never be used
    # in production but may be used as a template for other definitions
    - &OrdererOrg
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: OrdererOrg

        # ID to load the MSP definition as
        ID: OrdererMSP

        # MSPDir is the filesystem path which contains the MSP configuration
        MSPDir: crypto-config/ordererOrganizations/example.com/msp

        # AdminPrincipal dictates the type of principal used for an organization's Admins policy
        # Today, only the values of Role.ADMIN ad Role.MEMBER are accepted, which indicates a principal
        # of role type ADMIN and role type MEMBER respectively
        AdminPrincipal: Role.MEMBER

    - &CellPhoneCompany1
        Name: CellPhoneCompany1MSP
        ID: CellPhoneCompany1MSP
        MSPDir: crypto-config/peerOrganizations/cellphonecompany1.example.com/msp
        AdminPrincipal: Role.MEMBER
        AnchorPeers:
            - Host: blockchain-cellphonecompany1peer1
              Port: 30510

    - &CellPhoneCompany2
        Name: CellPhoneCompany2MSP
        ID: CellPhoneCompany2MSP
        MSPDir: crypto-config/peerOrganizations/cellphonecompany2.example.com/msp
        AdminPrincipal: Role.MEMBER
        AnchorPeers:
            - Host: blockchain-cellphonecompany2peer1
              Port: 30610

    - &CellPhoneCompany3
        Name: CellPhoneCompany3MSP
        ID: CellPhoneCompany3MSP
        MSPDir: crypto-config/peerOrganizations/cellphonecompany3.example.com/msp
        AdminPrincipal: Role.MEMBER
        AnchorPeers:
            - Host: blockchain-cellphonecompany3peer1
              Port: 30710

    - &Hospital1
        Name: Hospital1MSP
        ID: Hospital1MSP
        MSPDir: crypto-config/peerOrganizations/hospital1.example.com/msp
        AdminPrincipal: Role.MEMBER
        AnchorPeers:
            - Host: blockchain-hospital1peer1
              Port: 30810

    - &Hospital2
        Name: Hospital2MSP
        ID: Hospital2MSP
        MSPDir: crypto-config/peerOrganizations/hospital2.example.com/msp
        AdminPrincipal: Role.MEMBER
        AnchorPeers:
            - Host: blockchain-hospital2peer1
              Port: 30910

    - &NGO1
        Name: NGO1MSP
        ID: NGO1MSP
        MSPDir: crypto-config/peerOrganizations/ngo1.example.com/msp
        AdminPrincipal: Role.MEMBER
        AnchorPeers:
            - Host: blockchain-ngo1peer1
              Port: 31310

    - &NGO2
        Name: NGO2MSP
        ID: NGO2MSP
        MSPDir: crypto-config/peerOrganizations/ngo2.example.com/msp
        AdminPrincipal: Role.MEMBER
        AnchorPeers:
            - Host: blockchain-ngo2peer1
              Port: 31110

    - &Government1
        Name: Government1MSP
        ID: Government1MSP
        MSPDir: crypto-config/peerOrganizations/government1.example.com/msp
        AdminPrincipal: Role.MEMBER
        AnchorPeers:
            - Host: blockchain-government1peer1
              Port: 31210
################################################################################
#
#   SECTION: Orderer
#
#   - This section defines the values to encode into a config transaction or
#   genesis block for orderer related parameters
#
################################################################################
Orderer: &OrdererDefaults

    # Orderer Type: The orderer implementation to start
    # Available types are "solo" and "kafka"
    OrdererType: solo

    Addresses:
        - blockchain-orderer:31010

    # Batch Timeout: The amount of time to wait before creating a batch
    BatchTimeout: 2s

    # Batch Size: Controls the number of messages batched into a block
    BatchSize:

        # Max Message Count: The maximum number of messages to permit in a batch
        MaxMessageCount: 10

        # Absolute Max Bytes: The absolute maximum number of bytes allowed for
        # the serialized messages in a batch.
        AbsoluteMaxBytes: 99 MB

        # Preferred Max Bytes: The preferred maximum number of bytes allowed for
        # the serialized messages in a batch. A message larger than the preferred
        # max bytes will result in a batch larger than preferred max bytes.
        PreferredMaxBytes: 512 KB

    Kafka:
        # Brokers: A list of Kafka brokers to which the orderer connects
        # NOTE: Use IP:port notation
        Brokers:
            - 127.0.0.1:9092

    # Organizations is the list of orgs which are defined as participants on
    # the orderer side of the network
    Organizations:

################################################################################
#
#   SECTION: Application
#
#   - This section defines the values to encode into a config transaction or
#   genesis block for application related parameters
#
################################################################################
Application: &ApplicationDefaults

    # Organizations is the list of orgs which are defined as participants on
    # the application side of the network
    Organizations:

################################################################################
#
#   Profile
#
#   - Different configuration profiles may be encoded here to be specified
#   as parameters to the configtxgen tool
#
################################################################################
Profiles:

    CadanacOrdererGenesis:
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *CellPhoneCompany1
                    - *CellPhoneCompany2
                    - *CellPhoneCompany3
                    - *Hospital1
                    - *Hospital2
                    - *NGO1
                    - *NGO2
                    - *Government1
    ProfilePersonLocation:
        Consortium: SampleConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *CellPhoneCompany1
                - *CellPhoneCompany2
                - *CellPhoneCompany3
                - *Government1
    ProfilePersonHealth:
        Consortium: SampleConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Hospital1
                - *Hospital2
                - *Government1
    ProfileHealthFinance:
        Consortium: SampleConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Hospital1
                - *Hospital2
                - *NGO1
                - *NGO2
                - *Government1
