apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: cadanac-v0-1
  labels:
    name: kafka
spec:
  ports:
  - port: 9092
    name: kafka-port
    protocol: TCP
    nodePort: 31689
  selector:
    app: kafka
    id: "0"
  type: LoadBalancer
