kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka-broker0
  namespace: cadanac-v0-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
        id: "0"
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ADVERTISED_PORT
          value: "31689"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: 35.208.28.246
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zoo1:2181
        - name: KAFKA_BROKER_ID
          value: "0"
        - name: KAFKA_CREATE_TOPICS
          value: cadanac-topic:1:1
